/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.research;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.File;
import java.io.PrintWriter;
import java.util.List;
import java.util.concurrent.Callable;

@Command(name = "PublicApiAnalyzer", description = "Generates a report for provided JAR files.")
public class PublicApiAnalyzer implements Callable<Integer> {

    @Option(names = "--classpath", required = true, description = "JAR or directory to analyze")
    private List<File> classpath;

    @Option(names = "--output", required = true, description = "Output file for the report")
    private File output;

    public static void main(String... args) {
        int exitCode = new CommandLine(new PublicApiAnalyzer()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception {
        assert output.getParentFile().mkdirs();
        try (PrintWriter writer = new PrintWriter(output)) {
            new ReportGenerator(classpath, writer).generateReport();
        }
        System.out.println("Report generated at " + output.getAbsolutePath());
        return 0;
    }
}
